---
title: "index"
author: Justin Hamilton and Josh Rubin
embed-resources: true
format: html
editor: source
editor_options: 
  chunk_output_type: console
---

## Data source
[IPUMS USA](www.ipums.org) 

## Load IPUMS data
```{r}
#| warning: false
#| message: false

# install.packages("ipumsr")
library(ipumsr)
# NOTE: To load data, you must download both the extract's data and the DDI
# and also set the working directory to the folder with these files (or change the path below).

if (!require("ipumsr")) stop("Reading IPUMS data into R requires the ipumsr package. It can be installed using the following command: install.packages('ipumsr')")

ddi <- read_ipums_ddi("usa_00043.xml")
data <- read_ipums_micro(ddi)
```

## Distribution of usual hours worked by gender
```{r}
#| warning: false
#| message: false

library(tidyverse)

data |>
  filter(AGE > 15 & WKSWORK1 > 0) |>
  mutate(
    UHRSWORK = ifelse(UHRSWORK == 99, NA, UHRSWORK)
  ) |>
  ggplot(mapping = aes(x = UHRSWORK, y = factor(SEX))) +
  geom_boxplot(
    outlier.shape = NA, 
    width = 0.5, 
    staplewidth = 0.4, 
    median.linewidth = 1.5) +
  labs(
    title = "Distribution of usual hours worked by gender, 2024",
    subtitle = "Among individuals over 15 years and worked last year",
    caption = "Note: Bolded lines represent the median hours worked."
  ) +
  scale_y_discrete(
    name = "Sex",                         
    labels = c("1" = "Male", "2" = "Female")
  ) +
  xlab("Usual hours worked per week") +
  theme_minimal()
```

## Labor force participation rate by gender
```{r}
#| warning: false
#| message: false

lfpr_data <- data |>
  filter(AGE > 15 & LABFORCE != 0) |>
  mutate(
    LABFORCE = case_when(
      LABFORCE == 2 ~ 1,
      LABFORCE == 1 ~ 0,
      TRUE ~ NA
    ),
    sex_clean = ifelse(SEX == 1, "Male", "Female")
  ) |>
  group_by(sex_clean) |>
  summarize(
    LFPR = mean(LABFORCE, na.rm = TRUE)
  ) 

ggplot(data = lfpr_data, mapping = aes(x = sex_clean, y = LFPR, fill = sex_clean)) +
  geom_bar(stat = "identity", width = 0.5) +
  geom_text(
    mapping = aes(label = scales::percent(LFPR, accuracy = 0.1)),
    vjust = -1) +
  labs(
    title = "Labor force participation rate by gender, 2024",
    subtitle = "Among individuals over 15 years"
  ) +
  scale_y_continuous(labels = scales::percent) +
  xlab("Sex") +
  ylab("Labor force participation rate (%)") +
  theme_minimal() +
  theme(legend.position = "none") 
  
```

## Labor force participation rate differences by marital status and gender
```{r}
#| warning: false
#| message: false

lfpr_gender_mar <- data |>
  filter(AGE > 15, LABFORCE != 0) |>
  mutate(
    LABFORCE = case_when(
      LABFORCE == 2 ~ 1,
      LABFORCE == 1 ~ 0,
      TRUE ~ NA
      )
  ) |>
  group_by(SEX, MARST) |>
  summarize(lfpr = mean(LABFORCE, na.rm = TRUE))

lfpr_gender_mar |>
  ggplot() +
  geom_col(aes(x = factor(MARST), y = lfpr, fill = factor(SEX)), position = "dodge") +
  labs(
    title = "Labor Force Participation Rate by Gender and Marital Status",
    subtitle = "Among individuals 16 years and older",
    x = "Marital Status",
    y = "Labor Force Participation Rate",
    fill = "Gender"
  ) +
  scale_y_continuous(labels = scales::label_percent()) +
  scale_x_discrete(labels = c(
    "1" = "Married, spouse present",
    "2" = "Married, spouse absent",
    "3" = "Separated",
    "4" = "Divorced",
    "5" = "Widowed",
    "6" = "Never married/single"
    )) +
  scale_fill_discrete(labels = c(
    "1" = "Male",
    "2" = "Female"
    )) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)
  )

```

## Relationship between state education levels and labor force participation rate
```{r}
#| warning: false
#| message: false

state_data <- data %>%
  filter(AGE > 15, EDUC != 0, LABFORCE != 0) %>%
  mutate(
    LABFORCE = case_when(
      LABFORCE == 2 ~ 1,
      LABFORCE == 1 ~ 0,
      TRUE ~ NA
      ),
    COLLEGE = ifelse(
      EDUC >= 7,
      1,
      0
    )
  ) %>%
  group_by(STATEFIP) %>%
  summarize(
    LFPR = mean(LABFORCE, na.rm = TRUE),
    COLLEGE_PERC = mean(COLLEGE, na.rm = TRUE)
  )

state_data %>%
  ggplot() +
  geom_point(aes(x = COLLEGE_PERC, y = LFPR)) +
  geom_smooth(aes(x = COLLEGE_PERC, y = LFPR), se = FALSE, method = "lm", color = "skyblue1") +
  labs(
    title = "% of state residents with at least some college by labor force participation rate",
    subtitle = "Among individuals 16 years and older",
    x = "Percentage of Individuals with at least some college",
    y = "Labor Force Participation Rate"
  ) + 
  scale_y_continuous(labels = scales::label_percent()) +
  scale_x_continuous(labels = scales::label_percent()) +
  theme_minimal()

```
